# This field specifies the scheduler that will be started automatically when scx_loader starts (e.g., on boot).
default_sched = "scx_bpfland"

# This field specifies the mode which will be used when scx_loader starts (e.g., on boot).
default_mode = "powersave"